#!/bin/bash

BEGIN="${year}/01/01"
next_year=`expr $year + 1`
END="${next_year}/01/01"


echo -n -e $startBlue"Starting 401k contributions..."$endColor

ledger reg "^Assets:Portfolio:Paychex:401k" --limit "tag(\"TYPE\")=='TRADITIONAL'" \
-b $BEGIN -e $END \
> "${month_dir}401k-traditional-contributions.txt"

check_last_result

ledger reg "^Assets:Portfolio:Paychex:401k" --limit "tag(\"TYPE\")=='MATCH'" \
-b $BEGIN -e $END \
> "${month_dir}401k-match-contributions.txt"

check_last_result

echo -e $startGreenBold"DONE"$endColor


exit 0

