#!/bin/bash


echo -n -e $startBlue"Starting balance sheet reports..."$endColor

echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.fi/balance-sheet.sh)" \
> "${month_dir}balance-sheet.txt"

check_last_result

echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.fi/balance-sheet-market.sh)" \
> "${month_dir}balance-sheet-market.txt"

check_last_result

echo -e $startGreenBold"DONE"$endColor


# echo -n -e $startBlue"Starting balance sheet..."$endColor
# # balance sheet should be cumulative up to and including the reporting month
# # only show real (-R) accounts
# ledger bal -R -p monthly until $until_date --now $now_date -c \
# > $month_dir"balance-sheet.txt"

# check_last_result
# echo -e $startGreenBold"DONE"$endColor


# echo -n -e $startBlue"Starting balance sheet market value..."$endColor
# ledger bal -R -p monthly until $until_date -X $ --price-db $LEDGER_PRICES --now $now_date -c \
# > $month_dir"balance-sheet-market.txt"

# check_last_result
# echo -e $startGreenBold"DONE"$endColor

exit 0
