#!/bin/bash


echo -n -e $startBlue"Starting balance sheet reports..."$endColor


echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.fi/balance-sheet.sh)" \
> "${month_dir}balance-sheet.txt"

check_last_result


echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.fi/balance-sheet-market.sh)" \
> "${month_dir}balance-sheet-market.txt"

check_last_result


echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.fi/cc-rewards-snapshot.sh)" \
> "${month_dir}cc-rewards-snapshot.txt"

check_last_result


echo -e $startGreenBold"DONE"$endColor



exit 0

