#!/bin/bash


echo -n -e $startBlue"Starting cash flow reports..."$endColor

echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.fi/cash-flow.sh)" \
> "${month_dir}cash-flow.txt"

check_last_result

echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.fi/cash-flow-market.sh)" \
> "${month_dir}cash-flow-market.txt"

check_last_result

echo -e $startGreenBold"DONE"$endColor


# echo -n -e $startBlue"Starting cash flow report..."$endColor
# # cash flow report should be per month
# ledger bal ^Revenues ^Expenses -p $current_date --now $now_date -c \
# > $month_dir"cash-flow.txt"

# check_last_result
# echo -e $startGreenBold"DONE"$endColor


# echo -n -e $startBlue"Starting cash flow market report..."$endColor
# # cash flow report should be per month
# ledger bal ^Revenues ^Expenses -X $ --price-db $LEDGER_PRICES -p $current_date --now $now_date -c \
# > $month_dir"cash-flow-market.txt"

# check_last_result
# echo -e $startGreenBold"DONE"$endColor


exit 0
