#!/bin/bash


echo -n -e $startBlue"Starting graphs..."$endColor


export graph_dir="${month_dir}Graphs/"
create_dir $graph_dir


echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.graph/expenses-histogram.sh)" \
> "${graph_dir}monthly-expenses_histogram.svg"

check_last_result


echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.graph/income-area-plot.sh)" \
> "${graph_dir}income_area-graph.svg"

check_last_result


echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.graph/income-bar-plot.sh)" \
> "${graph_dir}income_bar-graph.svg"

check_last_result


echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.graph/net-worth-area-plot.sh)" \
> "${graph_dir}net-worth_area-graph.svg"

check_last_result


echo -e $startGreenBold"DONE"$endColor



exit 0

