#!/bin/bash

echo -n -e $startBlue"Starting monthly portfolio register..."$endColor


echo "$(/home/matt/Dropbox/journals/finances/accounting/ledger-reports/reports.fi/portfolio-monthly-register.sh)" \
> "${month_dir}portfolio-monthly-register.txt"

check_last_result


echo -e $startGreenBold"DONE"$endColor
