#!/bin/bash


echo -n -e "${startBlue}Starting monthly expense payees...${endColor}"
# same as monthly expense register except grouped by payees
ledger reg ^Expenses --group-by "payee" --subtotal --period-sort "(amount)" \
-p "${current_date}" -X $ --now "${now_date}" -c --price-db "${LEDGER_PRICES}" \
>| "${expense_dir}monthly-expense-payees.txt"

check_last_result
echo -e "${startGreenBold}DONE${endColor}"


exit 0
