#!/bin/bash

BEGIN="${year}/01/01"
next_year=`expr $year + 1`
END="${next_year}/01/01"


echo -n -e $startBlue"Starting 401k contributions..."$endColor

ledger reg "^Assets:Portfolio:Paychex:401k" --limit "tag(\"TYPE\")=='TRADITIONAL'" \
-b $BEGIN -e $END \
> "${month_dir}/401k-contributions-ytd-traditional.txt"


ledger reg "^Assets:Portfolio:Paychex:401k" --limit "tag(\"TYPE\")=='MATCH'" \
-b $BEGIN -e $END \
> "${month_dir}/401k-contributions-ytd-match.txt"


ledger bal "^Assets:Portfolio:Paychex:401k" --pivot TYPE \
--limit "tag(\"TYPE\")" -b $BEGIN -e $END \
> "${month_dir}/401k-contributions-ytd.txt"


echo -e $startGreenBold"DONE"$endColor


exit 0

