#!/bin/bash


echo -n -e $startBlue"Starting balance sheet reports..."$endColor


echo "$($cwd/reports.fi/balance-sheet.sh)" \
> "${month_dir}/balance-sheet.txt"


echo "$($cwd/reports.fi/balance-sheet-market.sh)" \
> "${month_dir}/balance-sheet-market.txt"


echo "$($cwd/reports.fi/cc-rewards-snapshot.sh)" \
> "${month_dir}/cc-rewards-snapshot.txt"


echo -e $startGreenBold"DONE"$endColor



exit 0

