#!/bin/bash


echo -n -e $startBlue"Starting cash flow reports..."$endColor


echo "$($cwd/reports.fi/cash-flow.sh)" \
> "${month_dir}/cash-flow.txt"


echo "$($cwd/reports.fi/cash-flow-market.sh)" \
> "${month_dir}/cash-flow-market.txt"


echo "$($cwd/reports.fi/revenue-ytd.sh)" \
> "${month_dir}/revenues-ytd.txt"


echo "$($cwd/reports.fi/expense-ytd.sh)" \
> "${month_dir}/expenses-ytd.txt"


echo "$($cwd/reports.fi/gasoline-ytd.sh)" \
> "${month_dir}/gasoline-ytd.txt"


echo "$($cwd/reports.fi/savings-rate.sh)" \
> "${month_dir}/savings-rate.txt"


echo "$($cwd/reports.fi/drawdown.sh)" \
> "${month_dir}/drawdown.txt"


echo -e $startGreenBold"DONE"$endColor



exit 0
