#!/bin/bash


echo -n -e $startBlue"Starting IRA contributions..."$endColor

BEGIN="${year}/01/01"
next_year=`expr $year + 1`
END="${next_year}/01/01"

ledger reg "Contributions:${year}:Vanguard:Roth IRA" \
-e $END \
> "${month_dir}/ira-contributions.txt"

# ledger bal ^Contributions --now $now_date -c \
# > "${investments_dir}ira-contributions.txt"

# check_last_result


echo -e $startGreenBold"DONE"$endColor


exit 0


# echo -n -e "${startBlue}Starting IRA contributions (by fund) report...${endColor}"

# ledger bal ^Contributions --pedantic --now $now_date -c --pivot IRA \
# > "${investments_dir}ira-contributions-fund.txt"

# check_last_result
# echo -e "${startGreenBold}DONE${endColor}"
