#!/bin/bash


# --exchange (-X) is similar to --market except it does not honor primary or secondary commodities (p.38).

# --now defines the current date in case you want to calculate in the past or future. This is useful
# for when using --market or --exchange to value the commodities as of that date.
# The default VALUE property for every commodity is
# = expr commodity == "commodity"
#     ; VALUE:: market(amount, date, exchange)
# where date is either today's date or the date defined by --now
# and exchange is either the primary commodity for the transaction or the value defined by --exchange.
# --now is useful with --current (-c) to limit the transactions to postings with dates <= to the date defined
# by --now.

echo -n -e $startBlue"Starting net worth reports..."$endColor

echo "$($cwd/reports.fi/net-worth.sh)" \
> "${month_dir}/net-worth.txt"


echo "$($cwd/reports.fi/net-worth-market.sh)" \
> "${month_dir}/net-worth-market.txt"


echo -e $startGreenBold"DONE"$endColor


exit 0
