#!/bin/bash


echo -n -e $startBlue"Starting assets percentage report..."$endColor
# asset percentage report should be reported the same as the asset market value report
ledger bal ^Assets --price-db $LEDGER_PRICES -X $ --now $now_date -c --percent \
-p monthly until $until_date > $asset_dir"assets-percentage.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor


exit 0
