#!/bin/bash


echo -n -e $startBlue"Starting assets market value report..."$endColor
# asset market value should be cumulative up to and including the reporting month
ledger bal ^Assets --price-db $LEDGER_PRICES -X $ --now $now_date -c \
-p monthly until $until_date > $asset_dir"assets-market-value.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor


exit 0
