#!/bin/bash


# Cumulative all time credit card rewards
echo -n -e $startBlue"Starting cumulative credit card rewards report..."$endColor
# ledger bal ^Revenues:Rewards -R -e $until_date --limit "has_tag('CREDIT')" --now $now_date -c \
ledger bal "/^Revenues:Rewards:(Discover it|Huntington Voice|Citi Double Cash)/" \
-f $LEDGER_FILE --price-db $LEDGER_PRICES \
-e $until_date --now $now_date -c -R -X $ \
> $rewards_dir"rewards-cumulative.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor



echo -n -e $startBlue"Starting monthly credit card rewards report..."$endColor

ledger bal "/^Revenues:Rewards:(Discover it|Huntington Voice|Citi Double Cash)/" \
-f $LEDGER_FILE --price-db $LEDGER_PRICES \
-b $current_date -e $until_date --now $now_date -c \
-R -X $ \
> $rewards_dir"rewards-monthly-market.txt"
# --limit "has_tag('CREDIT')"

check_last_result
echo -e $startGreenBold"DONE"$endColor


