#!/bin/bash


echo -n -e $startBlue"Starting variable expense report..."$endColor
ledger bal ^Expenses --limit "has_tag('VARIABLE')" --no-total -p $current_date \
-X $ --now $now_date -c --price-db $LEDGER_PRICES \
> $expense_dir"variable-expenses.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor


exit 0
