#!/bin/bash


echo -n -e $startBlue"Starting monthly expense register..."$endColor
# monthly expense register should be per month
ledger reg ^Expenses --period-sort "(amount)" -p $current_date \
-X $ --now $now_date -c --price-db $LEDGER_PRICES \
> $expense_dir"monthly-expense-register.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor


exit 0
