#!/bin/bash


# TODO: don't use the current market value for fees?
# TODO: compare portfolio fees at time of market to what those fees would be worth in the current market

fees_dir="${investments_dir}Fees/"
create_dir $fees_dir


echo -n -e $startBlue"Starting portfolio fees report..."$endColor
# i'm also currently thinking that this should be cumulative too
ledger bal "^Expenses:Fees:Portfolio" -f "${LEDGER_FILE}" --pivot SYM --no-total --invert \
--now $now_date -c -R --pedantic \
> "${fees_dir}portfolio-fees.txt"

check_last_result


ledger bal "^Expenses:Fees:Portfolio" -f "${LEDGER_FILE}" --pivot SYM --price-db "${LEDGER_PRICES}" \
-X $ --now $now_date -c --no-total --invert -R --pedantic \
> "${fees_dir}portfolio-fees-market.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor


exit 0
