#!/bin/bash


# ledger bal ^Capital Gains --no-total --pivot SYMBOL \
# --invert > $investments_dir"capital-gains.txt"


capitalgains_dir="${investments_dir}CapitalGains/"
create_dir $capitalgains_dir


echo -n -e $startBlue"Starting capital gains report..."$endColor
# i'm currently thinking that capital gains should be cumulative from month to month
ledger bal "^Revenues:Portfolio:Capital Gains" -f "${LEDGER_FILE}" --pivot SYM --no-total --invert \
--now $now_date -c -R --pedantic \
> "${capitalgains_dir}capital-gains.txt"
# ledger bal ^Revenues:Capital Gains --invert --no-total --now $now_date -c \
# > "${capitalgains_dir}capital-gains.txt"

check_last_result


# ledger bal ^Revenues:Capital Gains --invert --no-total --price-db $LEDGER_PRICES -X $ --now $now_date -c \
# > "${capitalgains_dir}capital-gains-market.txt"
ledger bal "^Revenues:Portfolio:Capital Gains" -f "${LEDGER_FILE}" --pivot SYM --price-db "${LEDGER_PRICES}" \
-X $ --now $now_date -c --no-total --invert -R --pedantic \
> "${capitalgains_dir}capital-gains-market.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor


exit 0
