#!/bin/bash

echo -n -e "${startBlue}Starting cost basis report...${endColor}"
# cost basis report is the same as the net worth report except calculates how much of our own money
# including reinvested dividends and reinvested capital gains we have invested for tax purposes.
# sometimes referred to as the tax basis.
"/home/matt/Dropbox/projects/ledger-utils/src/main.js" --cost --date $now_date \
> "${investments_dir}cost-basis.txt"

check_last_result
echo -e "${startGreenBold}DONE${endColor}"

exit 0

