#!/bin/bash


# ledger bal Income:Dividend --no-total --pivot SYMBOL --invert \
# --market > $investments_dir"dividends-total.txt"

# ledger bal Income:Dividend --no-total --limit "has_tag('INCOME')" \
# --pivot SYMBOL --invert --market > $investments_dir"dividends-income.txt"
#
# check_last_result
#
# ledger bal Income:Dividend --no-total --limit "has_tag('SPECIAL')" \
# --pivot SYMBOL --invert --market > $investments_dir"dividends-special.txt"
#
# check_last_result


# TODO: don't use the current market value for dividends either


echo -n -e $startBlue"Starting dividends report(s)..."$endColor
ledger bal ^Revenues:Dividend --no-total --invert --now $now_date -c \
> "${dividend_dir}dividends.txt"


ledger bal ^Revenues:Dividend --no-total --invert --price-db $LEDGER_PRICES -X $ --now $now_date -c \
> "${dividend_dir}dividends-market.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor


exit 0
