#!/bin/bash


# ledger bal Income:Dividend --no-total --pivot SYMBOL --invert \
# --market > $investments_dir"dividends-total.txt"

# ledger bal Income:Dividend --no-total --limit "has_tag('INCOME')" \
# --pivot SYMBOL --invert --market > $investments_dir"dividends-income.txt"
#
# check_last_result
#
# ledger bal Income:Dividend --no-total --limit "has_tag('SPECIAL')" \
# --pivot SYMBOL --invert --market > $investments_dir"dividends-special.txt"
#
# check_last_result


# TODO: don't use the current market value for dividends either


echo -n -e $startBlue"Starting dividends report(s)..."$endColor
# ledger bal ^Revenues:Dividend --no-total --invert --now $now_date -c \
# > "${dividend_dir}dividends.txt"
ledger bal ^Revenues:Portfolio:Dividend -f "${LEDGER_FILE}" --pivot SYM --no-total --invert \
--now $now_date -c -R --pedantic \
> "${dividend_dir}dividends.txt"


# ledger bal ^Revenues:Dividend --no-total --invert --price-db $LEDGER_PRICES -X $ --now $now_date -c \
# > "${dividend_dir}dividends-market.txt"
ledger bal ^Revenues:Portfolio:Dividend -f "${LEDGER_FILE}" --pivot SYM --price-db "${LEDGER_PRICES}" \
-X $ --now $now_date -c --no-total --invert -R --pedantic \
> "${dividend_dir}dividends-market.txt"


# dividend register report
ledger reg "Assets:Portfolio" -f "${LEDGER_FILE}" -b "${current_date}" -e "${until_date}" \
--now "${now_date}" -T "" --lot-prices --format \
"%(ansify_if( \
ansify_if(justify(format_date(date), int(date_width)), \
green if color and date > today), \
bold if should_bold)) \
%(ansify_if( \
ansify_if(justify(truncated(payee, int(payee_width)), int(payee_width)), \
bold if color and !cleared and actual), \
bold if should_bold)) \
%(ansify_if( \
ansify_if(justify(truncated(display_account, int(account_width), \
int(abbrev_len)), int(account_width)), \
blue if color), \
bold if should_bold)) \
%(ansify_if( \
justify(scrub(display_amount), int(amount_width), \
3 + int(meta_width) + int(date_width) + int(payee_width) \
+ int(account_width) + int(amount_width) + int(prepend_width), \
true, color), \
bold if should_bold)) \
%(ansify_if( \
justify(scrub(display_total), int(total_width), \
4 + int(meta_width) + int(date_width) + int(payee_width) \
+ int(account_width) + int(amount_width) + int(total_width) \
+ int(prepend_width), true, color), \
bold if should_bold))\n%/ \
%(justify(\" \", int(date_width))) \
%(ansify_if( \
justify(truncated(has_tag(\"Payee\") ? payee : \" \", \
int(payee_width)), int(payee_width)), \
bold if should_bold)) \
%$3 %$4 %$5 \
%(justify((market(display_total, date, '$')), 20, -1, true, color))\n" \
> "${dividend_dir}dividends-reg.txt"


check_last_result
echo -e $startGreenBold"DONE"$endColor


exit 0
