#!/bin/bash


echo -n -e $startBlue"Starting IRA contributions (yearly) report..."$endColor

ledger bal ^Contributions --now $now_date -c \
> "${investments_dir}ira-contributions-yearly.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor


echo -n -e "${startBlue}Starting IRA contributions (by fund) report...${endColor}"

ledger bal ^Contributions --pedantic --now $now_date -c --pivot IRA \
> "${investments_dir}ira-contributions-fund.txt"

check_last_result
echo -e "${startGreenBold}DONE${endColor}"
