#!/bin/bash


echo -n -e $startBlue"Starting ira contributions report..."$endColor

ledger bal ^Contributions --now $now_date -c \
> "${investments_dir}ira-contributions.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor
