#!/bin/bash


# ledger bal Fees:Portfolio --pivot SYMBOL --invert \
# --market > $investments_dir"portfolio-fees.txt"

# TODO: don't use the current market value for fees
# TODO: compare portfolio fees at time of market to what those fees would be worth in the current market


echo -n -e $startBlue"Starting portfolio fees report..."$endColor
# i'm also currently thinking that this should be cumulative too
ledger bal ^Expenses:Fees:Portfolio --invert --now $now_date -c \
> "${fees_dir}portfolio-fees.txt"

check_last_result


ledger bal ^Expenses:Fees:Portfolio --invert --price-db $LEDGER_PRICES -X $ --now $now_date -c \
> "${fees_dir}portfolio-fees-market.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor


exit 0
