#!/bin/bash


echo -n -e $startBlue"Starting accounts payable report..."$endColor
ledger bal ^Liabilities:Accounts Payable --group-by "payee" --empty --now $now_date -c \
> $liabilities_dir"accounts-payable.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor


exit 0
