#!/bin/bash


# ledger bal ^Liabilities --limit "has_tag('CREDIT')" \
# -p monthly until $until_date > $liabilities_dir"credit-cards.txt"

echo -n -e $startBlue"Starting credit card report..."$endColor
ledger bal "^Liabilities:Credit Card" -p monthly until $until_date --now $now_date -c \
> $liabilities_dir"credit-cards.txt"

check_last_result
echo -e $startGreenBold"DONE"$endColor


exit 0
